# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 20:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0009_auto_20180630_1953'),
        ('teachersapp', '0002_auto_20180630_1953'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('classname', models.CharField(max_length=50)),
                ('classcode', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_createdby', to=settings.AUTH_USER_MODEL)),
                ('sessions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_year', to='mainapp.Sessions')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachersapp.TeacherProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
