# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_years', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=250)),
                ('schoolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_session', to='mainapp.School')),
            ],
        ),
    ]
