# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_sessons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sessons',
            new_name='Sessions',
        ),
    ]
