# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180630_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='affliated_by',
            field=models.CharField(default=False, max_length=120),
        ),
        migrations.AddField(
            model_name='school',
            name='board_type',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
