# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classname',
            field=models.CharField(max_length=50),
        ),
    ]
