# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20180630_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='class',
            name='sessions',
        ),
        migrations.AddField(
            model_name='school',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sessions',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sessions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
